import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";


const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Login | Saturn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${redHatDisplay.variable} antialiased`}
    >
      {children}
    </div>
  );
}
